/* ===================================================================
   PRESET SECTOR DATA
   Framework reads drafted from public order-book disclosures, brokerage
   notes and management commentary available as of early 2026. Treat
   these as a starting file, not a verdict — confirm the current
   quarter's numbers before acting, the same way the framework itself
   expects ongoing re-verification.
=================================================================== */

/* ===================================================================
   FULL SECTOR TAXONOMY (Screener.in classification)
   Every sector shows up in the dropdown. Only some have researched
   stock cards yet (see PRESET_SECTORS below) — the rest let you add
   a stock inline and build the file up as you go.
   Note: "Data Centre" and "Solar" are Tickertape-style thematic
   groupings rather than official Screener industry codes, added
   because they were requested directly — everything else here is
   the official 86-sector Screener list.
=================================================================== */
const ALL_SECTOR_NAMES = [
  "Aerospace & Defence", "Agro Chemicals", "Air Transport Service", "Alcoholic Beverages",
  "Auto Ancillaries", "Automobile", "Banks", "Bearings", "Cables",
  "Capital Goods - Electrical Equipment", "Capital Goods-Non Electrical Equipment",
  "Castings, Forgings & Fastners", "Cement", "Cement - Products", "Ceramic Products",
  "Chemicals", "Computer Education", "Construction", "Consumer Durables",
  "Credit Rating Agencies", "Crude Oil & Natural Gas", "Data Centre",
  "Diamond, Gems and Jewellery",
  "Diversified", "Dry cells", "E-Commerce/App based Aggregator", "Edible Oil", "Education",
  "Electronics", "Engineering", "Entertainment", "ETF", "Ferro Alloys", "Fertilizers",
  "Finance", "Financial Services", "FMCG", "Gas Distribution", "Glass & Glass Products",
  "Healthcare", "Hotels & Restaurants", "Infrastructure Developers & Operators",
  "Infrastructure Investment Trusts", "Insurance", "IT - Hardware", "IT - Software",
  "Leather", "Logistics", "Marine Port & Services", "Media - Print/Television/Radio",
  "Mining & Mineral products", "Miscellaneous", "Non Ferrous Metals", "Oil Drill/Allied",
  "Online Media", "Packaging", "Paints/Varnish", "Paper", "Petrochemicals",
  "Pharmaceuticals", "Plantation & Plantation Products", "Plastic products",
  "Plywood Boards/Laminates", "Power Generation & Distribution", "Power Infrastructure",
  "Printing & Stationery", "Quick Service Restaurant", "Railways",
  "Readymade Garments/ Apparells", "Real Estate Investment Trusts", "Realty",
  "Refineries", "Refractories", "Retail", "Sanitaryware", "Ship Building", "Shipping",
  "Solar", "Steel", "Stock/ Commodity Brokers", "Sugar", "Telecom-Handsets/Mobile",
  "Telecomm Equipment & Infra Services", "Telecomm-Service", "Textiles",
  "Tobacco Products", "Trading", "Tyres",
  // Additional thematic groupings (Tickertape-style, not official Screener codes) — added by request
  "Gold Loan Finance", "Affordable Housing Finance", "Micro Finance", "Steel Pipes",
  "Middle Class Apparel", "Water EPC", "Heavy Engineering Equipment", "CDMO",
];

const PRESET_SECTORS = [
  {
    name: "Aerospace & Defence",
    stocks: [
      {
        ticker: "BEL", company: "Bharat Electronics",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "no" },
        requirementNotes: {
          relevant: "Sole/lead supplier on most Indian radar, EW and comms programmes — hard to displace.",
          leadingvar: "DAC approvals at an all-time high in FY26; order-awarding momentum expected to keep rising into FY27/28.",
          twoconfirm: "Disclosed order book (~₹76,000cr+) and rising capex allocation both point the same way.",
          cashevidence: "PSU with steady dividends and healthy margins, but working capital scales with the size of the book.",
          priceold: "This is the weak leg — the story is already the market's consensus pick in defence electronics.",
        },
        kinds: { demand: true, formalisation: true },
        operating: { volumes: true, repeat: true, capacityutil: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Book-to-bill sits around 4x industry-wide per brokerage notes (Aug 2026) — the open question for BEL specifically is no longer 'will orders come' but 'can execution keep pace.' Best used as a Stage-4 consensus holding, not a fresh discovery.",
      },
      {
        ticker: "SOLARINDS", company: "Solar Industries",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "Defence ordnance/explosives arm ramping off a much smaller base than BEL/HAL, plus export growth.",
          twoconfirm: "Management guidance of 25-30% revenue growth for FY26, alongside a defence order book still small relative to the civil explosives business.",
          priceold: "Already up sharply over five years — check whether the current price still leaves room, or has run ahead of the ramp.",
        },
        kinds: { demand: true, formalisation: true },
        operating: { repeat: true, marketshare: true },
        cash: { selffunded: true, roic: true },
        falsepositives: {},
        notes: "The core civil explosives business is cash-generative and appears to be funding the defence capacity build without heavy dilution — worth checking segment-wise disclosure to confirm this isn't manufactured through the parent's cash rather than the defence unit's own economics.",
      },
      {
        ticker: "BDL", company: "Bharat Dynamics",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "Missile/ammunition PSU with brokerages guiding even higher growth (25-30%) than larger DPSU peers off a smaller base.",
          twoconfirm: "Order book growth is disclosed; margin trajectory alongside it is less consistently confirmed quarter to quarter.",
        },
        kinds: { demand: true, formalisation: true },
        operating: { repeat: true },
        cash: {},
        falsepositives: { noorderbook: false },
        notes: "Smaller and less consensus-crowded than BEL/HAL — worth the two-question test from the framework: who will buy the output, and at what margin, before treating the order book alone as confirmation.",
      },
    ],
  },

  {
    name: "Capital Goods - Electrical Equipment",
    stocks: [
      {
        ticker: "WAAREEENER", company: "Waaree Energies",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "India's solar module manufacturing capacity roughly doubled industry-wide in a year (74GW to 172GW by March 2026) as ALMM rules shift domestic demand toward domestic makers.",
          twoconfirm: "Capacity expansion and the ALMM-driven order shift are two independent, publicly verifiable confirmations.",
          cashevidence: "Capital-intensive ramp — check whether the expansion is debt-funded or self-funded before trusting the growth.",
        },
        kinds: { capacity: true, formalisation: true },
        operating: { capacityutil: true, volumes: true },
        cash: {},
        falsepositives: {},
        notes: "This is a capex-to-cash bridge story first — use section F to track where Waaree's incremental capacity actually sits (commissioned vs. utilised vs. cash-generating) rather than reading the capacity announcement itself as demand.",
      },
      {
        ticker: "SUZLON", company: "Suzlon Energy",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "partial" },
        requirementNotes: {
          leadingvar: "Per ICRA (Jan 2026), wind OEM order books have surpassed annual manufacturing capacity industry-wide — a genuine capacity-utilisation confirmation, not a story.",
          cashevidence: "Suzlon's own balance-sheet repair (debt paydown after its earlier restructuring) is a textbook example of the framework's balance-sheet-repair kind of inflection.",
        },
        kinds: { capacity: true, balancesheet: true },
        operating: { capacityutil: true, volumes: true },
        cash: { debtfalling: true, ocf: true },
        falsepositives: {},
        notes: "A rare case where two different kinds of inflection (capacity utilisation + balance-sheet repair) are confirming each other at once — worth the higher conviction that implies, provided the order book keeps converting into billed revenue.",
      },
      {
        ticker: "PREMIERENE", company: "Premier Energies",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "Integrated solar cell and module capacity ramp, riding the same ALMM-driven domestic shift as Waaree.",
          twoconfirm: "Newer listing — fewer quarters of disclosed data to independently cross-check the capacity story yet.",
        },
        kinds: { capacity: true, formalisation: true },
        operating: { capacityutil: true },
        cash: {},
        falsepositives: {},
        notes: "Track the same capex-to-cash bridge as Waaree. Being a more recently listed, less-covered name than Waaree, there's more room for this to still be genuinely Stage 2 rather than already priced in.",
      },
      {
        ticker: "TRIL", company: "Transformers & Rectifiers (India)",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "Transformer order books across the industry are at multi-year highs on T&D capex, renewable integration and data-centre power demand.",
          twoconfirm: "Order book plus rising industry-wide capacity utilisation for transformer makers.",
        },
        kinds: { capacity: true, demand: true },
        operating: { capacityutil: true, volumes: true },
        cash: {},
        falsepositives: {},
        notes: "Smaller-cap names in this space are still mid-way through their own capex-to-cash bridge — check where this one specifically sits (commissioning vs. utilisation) before assuming the whole sector's tailwind applies equally.",
      },
      {
        ticker: "GEVERNOVA", company: "GE Vernova T&D India",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "no" },
        requirementNotes: { priceold: "Large, well-covered grid-equipment name — the T&D capex story is already the market's consensus view here." },
        kinds: { demand: true },
        operating: { volumes: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "A benchmark large-cap for the grid-capex theme rather than a fresh Stage-2 candidate.",
      },
    ],
  },

  {
    name: "Auto Ancillaries",
    stocks: [
      {
        ticker: "SONACOMS", company: "Sona BLW Precision Forgings",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "BEV driveline revenue share has been rising as a disclosed proportion of the overall mix, ahead of it showing up as a step-change in headline margins.",
          twoconfirm: "Company discloses both the BEV order book and the BEV revenue-mix percentage separately — two independent reads on the same shift.",
        },
        kinds: { product: true, demand: true },
        operating: { newproduct: true, marketshare: true },
        cash: {},
        falsepositives: {},
        notes: "Capex-heavy expansion to support new EV programmes — check free cash flow against the capex run-rate before assuming the growth is self-funded.",
      },
      {
        ticker: "UNOMINDA", company: "Uno Minda",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Steady content-per-vehicle gains across sensors, alloy wheels and EV components rather than one single product bet." },
        kinds: { demand: true, product: true },
        operating: { marketshare: true, volumes: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Diversified enough that no single product failure breaks the thesis — but that same diversification also makes it a slower, more consensus-priced compounder than a single-product Stage-2 bet.",
      },
      {
        ticker: "MOTHERSON", company: "Samvardhana Motherson International",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "no" },
        requirementNotes: { priceold: "Large, globally diversified tier-1 — already a conference-favourite auto-components name, so the crowd has largely priced the story in." },
        kinds: { demand: true },
        operating: { marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Useful as a scale benchmark for the sector rather than a fresh inflection candidate — most of the asymmetry here has already been arbitraged away.",
      },
    ],
  },

  {
    name: "Electronics",
    stocks: [
      {
        ticker: "DIXON", company: "Dixon Technologies",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "no" },
        requirementNotes: {
          leadingvar: "Shifting from pure contract assembly (thin margin) toward components — display modules, camera modules — which carry structurally higher margin.",
          priceold: "Already a well-owned PLI/EMS proxy; the market prices continued margin mix-shift as the base case.",
        },
        kinds: { product: true, formalisation: true },
        operating: { newproduct: true, marketshare: true },
        cash: {},
        falsepositives: {},
        notes: "The thesis now lives in the mix shift (components rising as % of revenue), not in headline revenue growth — track that percentage specifically each quarter.",
      },
      {
        ticker: "KAYNES", company: "Kaynes Technology",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "no" },
        requirementNotes: {
          leadingvar: "Core EMS business is confirmed and growing; the large semiconductor/OSAT packaging capex is still in the announced-to-commissioning phase.",
          twoconfirm: "Treat this as two separate cases stacked together — don't let confidence in the base EMS business bleed into confidence about the unproven semiconductor bet.",
        },
        kinds: { product: true, capacity: true },
        operating: { newproduct: true },
        cash: {},
        falsepositives: { noorderbook: false },
        notes: "A clean example of the framework's own warning: a capex announcement and a full order book are not demand. Use the capex-to-cash bridge below specifically for the semiconductor unit, separate from the core EMS read.",
      },
      {
        ticker: "AMBER", company: "Amber Enterprises",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "RAC (room AC) EMS plus a push into compressors — vertical integration similar in shape to Dixon's mix-shift story." },
        kinds: { product: true, formalisation: true },
        operating: { newproduct: true },
        cash: {},
        falsepositives: {},
        notes: "Demand is seasonal (summer-linked) — be careful not to read a strong summer quarter alone as a structural inflection; look for the compressor vertical-integration margin specifically.",
      },
    ],
  },

  {
    name: "Capital Goods-Non Electrical Equipment",
    stocks: [
      {
        ticker: "TRITURBINE", company: "Triveni Turbine",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Industrial steam turbine demand from both domestic capex and exports, converting steadily into revenue." },
        kinds: { demand: true },
        operating: { volumes: true, marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Longer, steadier track record than the newer transformer names — less asymmetric, but the confirmation is more mature.",
      },
      {
        ticker: "KIRLOSENG", company: "Kirloskar Pneumatic",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: {},
        kinds: { demand: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Smaller and less-covered industrial capex play — treat as an early, unconfirmed candidate rather than a settled read.",
      },
    ],
  },

  {
    name: "Railways",
    stocks: [
      {
        ticker: "TITAGARH", company: "Titagarh Rail Systems",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "no" },
        requirementNotes: {
          leadingvar: "Vande Bharat and metro coach order book is large and disclosed, but the stock already re-rated heavily in 2023-24 on that same story.",
          priceold: "Execution and margin delivery are now the swing factor, not order visibility — classic Stage 4.",
        },
        kinds: { demand: true, formalisation: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: { noorderbook: false },
        notes: "Watch margins specifically — an order book with no clear margin visibility behind it is one of the framework's named false positives, and railway EPC margins have historically been thin.",
      },
      {
        ticker: "RVNL", company: "Rail Vikas Nigam",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "no" },
        requirementNotes: {
          leadingvar: "Steady EPC order inflow from Indian Railways as a PSU project-execution arm.",
          priceold: "Already consensus-recognised — most of the operating story is in the price.",
        },
        kinds: { demand: true, formalisation: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: { noorderbook: false },
        notes: "Order inflow is steady but margins are thin and execution-dependent — the framework's 'order book has no execution capacity or margin visibility' flag deserves a real check here, not just a box-tick.",
      },
      {
        ticker: "IRCON", company: "Ircon International",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { priceold: "Less consensus-crowded than RVNL or Titagarh — more room left if the same order-book story plays out here too." },
        kinds: { demand: true, formalisation: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Smaller and less-owned than its railway EPC peers — worth the same margin-visibility check, but starting from a less priced-in base.",
      },
      {
        ticker: "KERNEX", company: "Kernex Microsystems",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "no", priceold: "yes" },
        requirementNotes: { leadingvar: "Train collision-avoidance (Kavach) signalling — a smaller, more specialised niche than the wagon/coach makers, riding the same railway safety-mandate push." },
        kinds: { formalisation: true, product: true },
        operating: {},
        cash: {},
        falsepositives: { noorderbook: false },
        notes: "Kavach rollout has been slower than initially guided industry-wide — check actual order execution against the mandate's timeline before trusting the order book alone.",
      },
      {
        ticker: "HBLENGINE", company: "HBL Engineering",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { leadingvar: "Diversified into railway signalling (including Kavach) from its legacy battery business — a business-mix shift similar in shape to Dixon's EMS-to-components story." },
        kinds: { product: true, formalisation: true },
        operating: { newproduct: true },
        cash: {},
        falsepositives: {},
        notes: "Track the signalling order book as a distinct line from the legacy battery business — don't let strength in one segment imply strength in the other.",
      },
      {
        ticker: "JWL", company: "Jupiter Wagons",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "no" },
        requirementNotes: { leadingvar: "Wagon manufacturing capacity ramp plus diversification into wagon leasing and electric mobility (buses)." },
        kinds: { demand: true, capacity: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: {},
        notes: "Already well-owned as a wagon-cycle proxy — the newer leasing and e-mobility bets are less proven than the core wagon business and deserve their own separate check.",
      },
    ],
  },

  {
    name: "Engineering",
    stocks: [
      {
        ticker: "THERMAX", company: "Thermax",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "Diversifying order book into green hydrogen and chemicals-linked capex on top of its traditional energy/environment business." },
        kinds: { demand: true, capacity: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: {},
        notes: "The new-energy order book is real but still small relative to the base business — check it's not being used to justify a re-rating of the whole company before it's material.",
      },
      {
        ticker: "PRAJIND", company: "Praj Industries",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Ethanol-blending policy has driven a multi-year domestic capex cycle for distillery equipment." },
        kinds: { demand: true, formalisation: true },
        operating: { volumes: true, repeat: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "A formalisation/regulation-driven inflection — the key falsifier to watch is any slowdown in the blending mandate itself, since the order book depends on that policy holding.",
      },
    ],
  },

  {
    name: "Consumer Durables",
    stocks: [
      {
        ticker: "VOLTAS", company: "Voltas",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "RAC demand plus PLI-linked component localisation, similar to the Amber/Dixon EMS story from the buyer's side." },
        kinds: { demand: true, formalisation: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: {},
        notes: "Same seasonal caution as Amber applies — separate a genuinely hot summer quarter from a durable share gain.",
      },
      {
        ticker: "HAVELLS", company: "Havells India",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "no" },
        requirementNotes: { priceold: "Large, well-owned consumer electricals name — already priced as a quality compounder." },
        kinds: { demand: true },
        operating: { marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "A benchmark quality name rather than a fresh inflection candidate.",
      },
      {
        ticker: "CROMPTON", company: "Crompton Greaves Consumer Electricals",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {},
        kinds: { demand: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Turnaround-in-progress story (management and distribution changes) — check governance/execution confirmations specifically before treating it as confirmed.",
      },
    ],
  },

  {
    name: "Textiles",
    stocks: [
      {
        ticker: "GOKEX", company: "Gokaldas Exports",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { leadingvar: "Apparel export order wins from US/Europe brands looking to diversify sourcing away from China ('China+1')." },
        kinds: { demand: true, capacity: true },
        operating: { volumes: true, newproduct: true },
        cash: {},
        falsepositives: { onecustomer: false },
        notes: "Check customer concentration specifically — a China+1 order win from one or two large brands can look like structural demand while really being a single-customer story.",
      },
      {
        ticker: "KPRMILL", company: "KPR Mill",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Vertically integrated (yarn to garment) with garmenting capacity expansion running ahead of peers." },
        kinds: { demand: true, capacity: true },
        operating: { volumes: true, capacityutil: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Vertical integration gives more independent confirmation points than a pure garmenter like Gokaldas — a genuinely stronger evidence base.",
      },
      {
        ticker: "WELSPUNLIV", company: "Welspun Living",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {},
        kinds: { demand: true },
        operating: {},
        cash: {},
        falsepositives: { onecustomer: false },
        notes: "Home textiles depend heavily on a handful of large US retail relationships — the same single-customer flag as Gokaldas applies, arguably more so.",
      },
    ],
  },

  {
    name: "Insurance",
    stocks: [
      {
        ticker: "ICICIGI", company: "ICICI Lombard General Insurance",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "no" },
        requirementNotes: { priceold: "Large, well-covered general insurer — insurance penetration story is already the market's base case here." },
        kinds: { formalisation: true },
        operating: { marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "A benchmark quality name in general insurance rather than a fresh inflection candidate.",
      },
      {
        ticker: "STARHEALTH", company: "Star Health and Allied Insurance",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "no", priceold: "yes" },
        requirementNotes: { cashevidence: "Claims ratio and combined ratio trends need close tracking — health insurers can show premium growth while underwriting quality deteriorates." },
        kinds: { formalisation: true, demand: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: { costcollapse: false },
        notes: "This is the sector's clearest case of the framework's own warning — 'inflection guilty until proven innocent' — because premium growth alone says nothing about claims experience. Check the combined ratio before the topline.",
      },
      {
        ticker: "NIVABUPA", company: "Niva Bupa Health Insurance",
        stage: 1,
        requirements: { relevant: "yes", leadingvar: "no", twoconfirm: "no", cashevidence: "no", priceold: "yes" },
        requirementNotes: { leadingvar: "Newer listing still building distribution scale — story stage, limited independent confirmation yet." },
        kinds: { formalisation: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Too early for most of the framework's confirmation checks — treat as a name to revisit once a few more quarters of claims and distribution data exist.",
      },
    ],
  },

  {
    name: "Logistics",
    stocks: [
      {
        ticker: "CONCOR", company: "Container Corporation of India",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "Dedicated Freight Corridor (DFC) sections are commissioning progressively, each one a potential step-change in rail logistics volume and transit time." },
        kinds: { capacity: true, formalisation: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: {},
        notes: "Structurally similar to the capex-to-cash bridge — track which DFC sections are actually commissioned and carrying volume versus still under construction, rather than the overall project announcement.",
      },
      {
        ticker: "TCIEXP", company: "TCI Express",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Organised express logistics gaining share from unorganised operators post-GST/e-way bill formalisation." },
        kinds: { formalisation: true, demand: true },
        operating: { marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "A cleaner formalisation story than most — the mechanism (GST compliance favouring organised players) is structural rather than cyclical.",
      },
      {
        ticker: "MAHLOG", company: "Mahindra Logistics",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "no", priceold: "yes" },
        requirementNotes: { cashevidence: "Asset-light 3PL model — margins have historically been thin; check whether scale is actually converting to profitability." },
        kinds: { formalisation: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Same formalisation tailwind as TCI Express, but thinner margins historically — the moat/right-to-win question in section E matters more here.",
      },
    ],
  },

  {
    name: "Diamond, Gems and Jewellery",
    stocks: [
      {
        ticker: "PNGJL", company: "P N Gadgil Jewellers",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "yes" },
        requirementNotes: {
          leadingvar: "Organised jewellery's share of the market has moved from roughly 35% to the high-30s/low-40s over the past few years, on hallmarking and GST-driven formalisation.",
          twoconfirm: "Store-count expansion and rising franchise revenue share are two independent reads on the same formalisation shift.",
          priceold: "A recent brokerage initiation (BOB Capital, Sep 2025) rated this one BUY while rating peers HOLD on valuation — worth checking whether that gap has already closed.",
        },
        kinds: { formalisation: true, demand: true },
        operating: { marketshare: true, volumes: true },
        cash: {},
        falsepositives: {},
        notes: "Same brokerage note flagged this as the more reasonably priced name in the pack relative to Kalyan/Senco/Thangamayil — check whether that gap still holds before assuming it's still the cheaper way to buy the same formalisation story.",
      },
      {
        ticker: "KALYANKJIL", company: "Kalyan Jewellers India",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "no" },
        requirementNotes: {
          leadingvar: "Aggressive store rollout (130 new showrooms guided for FY25 vs 71 in FY24) chasing Titan's scale.",
          priceold: "Same brokerage note rated this HOLD specifically on rich valuation, despite liking the underlying formalisation story.",
        },
        kinds: { formalisation: true, demand: true },
        operating: { marketshare: true, volumes: true },
        cash: {},
        falsepositives: {},
        notes: "The operating story here looks similar to PNG's, but the framework's fifth condition (price not already reflecting it) is the one that's failing — the crowd already owns this one.",
      },
      {
        ticker: "SENCO", company: "Senco Gold",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "no" },
        requirementNotes: { leadingvar: "Dominant in Eastern India (Bengal, Odisha), expanding pan-India off that regional base." },
        kinds: { formalisation: true },
        operating: { marketshare: true },
        cash: {},
        falsepositives: {},
        notes: "More regionally concentrated than Kalyan or Titan — check whether the pan-India expansion is actually converting, or whether growth is really just the home-market base compounding.",
      },
      {
        ticker: "THANGAMAYL", company: "Thangamayil Jewellery",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "no" },
        requirementNotes: { leadingvar: "Concentrated in Tamil Nadu — a smaller, single-region version of the same organised-retail story." },
        kinds: { formalisation: true },
        operating: {},
        cash: {},
        falsepositives: { onecustomer: false },
        notes: "Single-region concentration is this one's key risk to watch — not a false positive by itself, but worth confirming growth isn't just one state's festive calendar.",
      },
    ],
  },

  {
    name: "Solar",
    stocks: [
      {
        ticker: "WAAREERTL", company: "Waaree Renewable Technologies",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "The EPC/project-execution arm rather than the module-manufacturing business (that's the separately listed Waaree Energies) — a different risk profile riding the same demand wave." },
        kinds: { demand: true, formalisation: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: {},
        notes: "Don't conflate this with Waaree Energies — same parent group, but EPC execution risk and margin profile are meaningfully different from the manufacturing business.",
      },
      {
        ticker: "SWSOLAR", company: "Sterling & Wilson Renewable Energy",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "no", priceold: "yes" },
        requirementNotes: { cashevidence: "This name has a history of governance and balance-sheet stress (promoter pledge issues in prior years) — treat any recent recovery as a turnaround claim to verify, not a given." },
        kinds: { demand: true, balancesheet: true },
        operating: {},
        cash: {},
        falsepositives: { dilution: false },
        notes: "This is a genuine 'guilty until proven innocent' case — a large solar EPC order book means little here without independently confirming the balance sheet has actually been repaired since the earlier stress.",
      },
      {
        ticker: "WEBELSOLAR", company: "Websol Energy System",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "Solar cell manufacturing capacity expansion, riding the same ALMM-driven domestic-sourcing shift as the larger module makers." },
        kinds: { capacity: true, formalisation: true },
        operating: { capacityutil: true },
        cash: {},
        falsepositives: {},
        notes: "Small-cap capacity story — use the capex-to-cash bridge below specifically, since the gap between announced capacity and cash-generating utilisation tends to be wider for smaller balance sheets.",
      },
      {
        ticker: "ORIANA", company: "Oriana Power",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { leadingvar: "Smaller rooftop and commercial & industrial (C&I) solar EPC player — a more granular, less capital-intensive part of the same sector story." },
        kinds: { demand: true, formalisation: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "C&I rooftop solar depends on corporate capex budgets rather than utility-scale tenders — a different demand driver from the utility-scale names, worth verifying separately.",
      },
    ],
  },

  {
    name: "Data Centre",
    stocks: [
      {
        ticker: "ANANTRAJ", company: "Anant Raj",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "no", priceold: "partial" },
        requirementNotes: {
          leadingvar: "Pivoting from a pure real-estate developer into data centre infrastructure — signed a ₹20,000cr MOU with the Haryana government (Jun 2026) to scale IT load capacity from 28MW to 357MW by FY32.",
          cashevidence: "This is almost entirely a capex-to-cash bridge story right now — management has guided ₹1,200cr data-centre revenue by FY27, but that's still a target, not delivered cash flow.",
        },
        kinds: { product: true, capacity: true },
        operating: { newproduct: true },
        cash: {},
        falsepositives: { noorderbook: false },
        notes: "A textbook case of the framework's own warning: an MOU and a capacity target are not demand or cash flow yet. Use section F closely here — track MW actually commissioned and generating colocation revenue, not the headline MOU size.",
      },
      {
        ticker: "NETWEB", company: "Netweb Technologies India",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "no" },
        requirementNotes: {
          leadingvar: "Makes AI servers and data-centre hardware directly — a picks-and-shovels play on the same capex wave rather than the real estate/colocation side.",
          twoconfirm: "Reported Q1 revenue of ~₹301cr and net profit of ~₹30cr with sequential growth, alongside broad industry data-centre capacity guidance (1.3GW in 2024 to 5GW by 2030).",
          priceold: "Stock already re-rated sharply (40%+ in a single month per one Sep 2025 report) — check how much of the AI-hardware growth is already priced in.",
        },
        kinds: { demand: true, product: true },
        operating: { volumes: true, newproduct: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "More confirmed than Anant Raj since it already has recurring revenue and profit from hardware sales rather than a capacity target — but the valuation question (condition 5) needs a real check given how fast it's moved.",
      },
      {
        ticker: "E2E", company: "E2E Networks",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "GPU cloud provider — L&T acquired a 21% stake (~₹1,406cr) via preferential allotment and a promoter-stake purchase, and the company won a ₹177cr MeitY order under the IndiaAI Mission.",
          twoconfirm: "The L&T stake and the government order are two independent, publicly disclosed confirmations of the same AI-infrastructure thesis.",
        },
        kinds: { product: true, demand: true },
        operating: { newproduct: true, volumes: true },
        cash: {},
        falsepositives: {},
        notes: "This is the same company used as a case study in the original inflection-point framework article — GPU/AI cloud demand was visible in customer and workload counts before it showed up in headline profit. Revenue base is still small (~₹36cr quarterly) relative to the market-cap re-rating, so size the position accordingly.",
      },
      {
        ticker: "TECHNOE", company: "Techno Electric & Engineering",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "A second-order play — power transmission and infrastructure EPC feeding data-centre power demand, rather than owning the data centres themselves." },
        kinds: { demand: true },
        operating: { volumes: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Lower-torque, more diversified exposure to the theme than Anant Raj/Netweb/E2E — a way to participate in the data-centre capex wave without betting on any single operator's execution.",
      },
    ],
  },

  {
    name: "Credit Rating Agencies",
    stocks: [
      {
        ticker: "CRISIL", company: "CRISIL",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "no" },
        requirementNotes: { priceold: "Market leader with S&P as majority owner — already priced as a quality compounder, not a fresh discovery." },
        kinds: { formalisation: true },
        operating: {},
        cash: { ocf: true },
        falsepositives: {},
        notes: "A benchmark quality name in the ratings/analytics space — corporate bond market deepening is the long-term tailwind, but it's a slow, well-known one.",
      },
      {
        ticker: "CARERATING", company: "CARE Ratings",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "Smaller than CRISIL/ICRA with more room to gain share as bond issuance volumes grow, plus a governance clean-up since its earlier promoter-related troubles." },
        kinds: { formalisation: true, governance: true },
        operating: { marketshare: true },
        cash: {},
        falsepositives: {},
        notes: "The governance-change angle is real here (board and ownership changes after past issues) — worth verifying board quality and related-party cleanup specifically before trusting the growth numbers.",
      },
      {
        ticker: "ICRA", company: "ICRA",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "partial" },
        requirementNotes: {},
        kinds: { formalisation: true },
        operating: {},
        cash: { ocf: true },
        falsepositives: {},
        notes: "Moody's-backed, similar profile to CRISIL but smaller — a steady compounder rather than an asymmetric bet.",
      },
    ],
  },

  {
    name: "Cement",
    stocks: [
      {
        ticker: "ULTRACEMCO", company: "UltraTech Cement",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "no" },
        requirementNotes: { priceold: "Largest domestic player and the sector's consensus pick — most of the capacity-led growth story is already in the price." },
        kinds: { capacity: true, demand: true },
        operating: { volumes: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Useful as the sector benchmark for capacity utilisation and pricing trends rather than a fresh inflection candidate.",
      },
      {
        ticker: "JKCEMENT", company: "JK Cement",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "Aggressive capacity expansion in North/Central India plus a growing white cement and putty business that carries better margins than grey cement." },
        kinds: { capacity: true, product: true },
        operating: { capacityutil: true },
        cash: {},
        falsepositives: {},
        notes: "The white-cement/putty mix-shift is the more interesting margin story here than the grey-cement capacity add alone — track that segment specifically.",
      },
      {
        ticker: "NUVOCO", company: "Nuvoco Vistas",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "no", priceold: "yes" },
        requirementNotes: { cashevidence: "Carries meaningfully more debt than peers from its acquisition-led growth — a balance-sheet-repair story that hasn't fully confirmed yet." },
        kinds: { balancesheet: true, capacity: true },
        operating: {},
        cash: {},
        falsepositives: { dilution: false },
        notes: "This is a deleveraging story first, cement demand story second — check debt reduction progress before the capacity numbers.",
      },
      {
        ticker: "RAMCOCEM", company: "The Ramco Cements",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "South India-concentrated, benefiting from regional capacity discipline and infrastructure-led demand." },
        kinds: { demand: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Regional concentration cuts both ways — strong if South India capex holds up, more exposed than pan-India peers if it doesn't.",
      },
    ],
  },

  {
    name: "Gold Loan Finance",
    stocks: [
      {
        ticker: "MUTHOOTFIN", company: "Muthoot Finance",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "no" },
        requirementNotes: { priceold: "Market leader in organised gold loans — already the sector's consensus pick, benefiting from gold price rallies as much as any operating inflection." },
        kinds: { formalisation: true },
        operating: {},
        cash: { ocf: true },
        falsepositives: { otherincome: false },
        notes: "Watch out for gold-price-driven AUM growth being read as a business inflection — rising collateral value isn't the same as rising demand or market share.",
      },
      {
        ticker: "MANAPPURAM", company: "Manappuram Finance",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { leadingvar: "Diversifying beyond pure gold loans into microfinance and vehicle finance via subsidiaries — a mix-shift with its own separate risks." },
        kinds: { formalisation: true, product: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "The non-gold subsidiaries (including a microfinance arm) carry the same asset-quality risk flagged in the Micro Finance sector below — don't evaluate the gold-loan business in isolation from them.",
      },
      {
        ticker: "IIFL", company: "IIFL Finance",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "no", cashevidence: "no", priceold: "yes" },
        requirementNotes: { twoconfirm: "Had an RBI business restriction on its gold loan segment in 2024 over lending irregularities, later lifted — treat recovery as a claim to verify, not an assumption." },
        kinds: { governance: true, formalisation: true },
        operating: {},
        cash: {},
        falsepositives: { otherincome: false },
        notes: "A genuine governance-change candidate if remediation is real — check RBI's own commentary and subsequent audit findings before trusting management's account of the fix.",
      },
      {
        ticker: "CSBBANK", company: "CSB Bank",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "Gold loans are a large share of a small-bank balance sheet — concentration risk cuts differently here than at Muthoot/Manappuram." },
        kinds: { formalisation: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "A bank first, gold-loan-heavy second — funding cost and deposit growth matter as much here as the gold-loan book itself.",
      },
    ],
  },

  {
    name: "Affordable Housing Finance",
    stocks: [
      {
        ticker: "AAVAS", company: "Aavas Financiers",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Serves self-employed, informal-income borrowers in smaller towns — a formalisation-of-credit-access story as much as a housing one." },
        kinds: { formalisation: true, demand: true },
        operating: { marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Asset quality in this niche depends heavily on informal-income underwriting quality — worth checking credit cost trends specifically, not just AUM growth.",
      },
      {
        ticker: "HOMEFIRST", company: "Home First Finance",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { leadingvar: "Technology-led underwriting for first-time home buyers, expanding branch network into newer geographies." },
        kinds: { formalisation: true, demand: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: {},
        notes: "Newer branches take time to season — check vintage-wise asset quality on recent branches rather than the blended book average.",
      },
      {
        ticker: "APTUS", company: "Aptus Value Housing Finance",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "100% in-house sourcing and collections (no direct sales agents) — a structurally different, lower-risk model than peers who outsource origination." },
        kinds: { formalisation: true },
        operating: { marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "The in-house model is the moat question from section E — worth confirming it's holding as the company scales into new states, not just in its South India home base.",
      },
      {
        ticker: "AADHARHFC", company: "Aadhar Housing Finance",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {},
        kinds: { formalisation: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Largest pure-play affordable housing financier by AUM — a scale benchmark for the space rather than the most asymmetric name in it.",
      },
    ],
  },

  {
    name: "Micro Finance",
    stocks: [
      {
        ticker: "CREDITACC", company: "CreditAccess Grameen",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "no", priceold: "partial" },
        requirementNotes: {
          leadingvar: "Sector-wide MFI stress (ICRA put total stress at ~15% of the book in March 2025, versus 5.9% a year earlier) appears to be past its peak — CreditAccess showed a sequential rise in loan portfolio in the December 2025 quarter after a long decline.",
          cashevidence: "Profit is still recovering — Q1 FY26 net profit fell 85% year-on-year on higher provisions, though sequentially better than the prior quarter.",
        },
        kinds: { balancesheet: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: {},
        notes: "Widely seen as the best-placed large MFI to recover first (brokerages including JM Financial and Investec have flagged this). This is a genuine 'is the worst over' inflection call — the operating confirmation (portfolio growth resuming) is ahead of the cash confirmation (profit still provisioning-heavy), which is exactly the framework's Stage 2 pattern.",
      },
      {
        ticker: "FUSION", company: "Fusion Finance",
        stage: 1,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "no", cashevidence: "no", priceold: "yes" },
        requirementNotes: { leadingvar: "AUM shrank 37% year-on-year to ₹7,687cr (June 2025) as the company deliberately scaled down new-customer disbursements to control risk — now guiding new-customer share back up to 35% by March 2026." },
        kinds: { balancesheet: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Earlier and more damaged than CreditAccess Grameen — targeting ~₹200cr recovery from a ₹3,400cr stressed-asset book over 12 months. Treat this as a story/turnaround-claim stage until the recovery numbers actually show up, not yet a confirmed inflection.",
      },
      {
        ticker: "SPANDANA", company: "Spandana Sphoorty Financial",
        stage: 1,
        requirements: { relevant: "yes", leadingvar: "no", twoconfirm: "no", cashevidence: "no", priceold: "yes" },
        requirementNotes: { leadingvar: "Scaling back operations in weaker states (Kerala, Gujarat) while targeting ~20% AUM growth for FY26 — a story about future discipline, not yet demonstrated results." },
        kinds: { balancesheet: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "One of the more stressed names in the pack — the retrenchment plan is sensible on paper but unconfirmed; wait for at least one or two quarters of the new discipline showing up in numbers.",
      },
      {
        ticker: "SATIN", company: "Satin Creditcare Network",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "no", priceold: "yes" },
        requirementNotes: {},
        kinds: { balancesheet: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Same sector-wide 'is the worst over' question as the rest of this list — the whole Micro Finance theme is a false-positive minefield right now (a rebound in disbursements can look like recovery while credit costs are still working through the system), so lean hard on section D before trusting any single quarter's numbers.",
      },
    ],
  },

  {
    name: "Steel Pipes",
    stocks: [
      {
        ticker: "APLAPOLLO", company: "APL Apollo Tubes",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "no" },
        requirementNotes: { leadingvar: "Clear market leader in structural steel tubes, with continued capacity expansion and a value-added product mix shift (thinner, higher-margin tubes)." },
        kinds: { capacity: true, product: true },
        operating: { capacityutil: true, marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Already a well-owned compounder in this space — the mix-shift toward value-added products is the more interesting ongoing confirmation to track than volume growth alone.",
      },
      {
        ticker: "HARIOMPIPE", company: "Hariom Pipe Industries",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { leadingvar: "Smaller and newer-listed than APL Apollo, still expanding capacity and backward-integrating into billets." },
        kinds: { capacity: true },
        operating: { capacityutil: true },
        cash: {},
        falsepositives: {},
        notes: "Less consensus-owned than APL Apollo — worth the capex-to-cash bridge check specifically, since smaller balance sheets take longer to convert new capacity into cash flow.",
      },
      {
        ticker: "JTLIND", company: "JTL Industries",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: {},
        kinds: { capacity: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Smallest and least-covered of the three — treat as an early, unconfirmed candidate rather than a settled read.",
      },
    ],
  },

  {
    name: "Middle Class Apparel",
    stocks: [
      {
        ticker: "TRENT", company: "Trent",
        stage: 5,
        requirements: { relevant: "yes", leadingvar: "no", twoconfirm: "no", cashevidence: "partial", priceold: "no" },
        requirementNotes: { priceold: "This is the exact company used as the framework article's own Case Study 1 — its Zudio format's store-cohort inflection was visible years before the P&L confirmed it. That inflection has long since played out and been fully priced in." },
        kinds: { product: true, demand: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Kept here deliberately as the framework's own example of Stage 5 — current margins and store-growth assumptions are now doing most of the valuation work, which is precisely the extrapolation risk the article warns about.",
      },
      {
        ticker: "MANYAVAR", company: "Vedant Fashions",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Dominant in the organised ethnic-wear/wedding segment with an asset-light franchise model." },
        kinds: { formalisation: true, demand: true },
        operating: { marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Wedding-season demand is inherently lumpy — check same-store growth over a full year rather than any single strong quarter.",
      },
      {
        ticker: "GOCOLORS", company: "Go Fashion (India)",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { leadingvar: "Category-creator in women's bottom-wear (leggings/palazzos) as a distinct organised segment, still expanding store count." },
        kinds: { product: true, formalisation: true },
        operating: { newproduct: true },
        cash: {},
        falsepositives: {},
        notes: "A single-category bet — the moat question from section E (can a well-funded competitor copy this) matters more here than for diversified apparel names.",
      },
      {
        ticker: "ARVINDFASN", company: "Arvind Fashions",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "Licensed-brand portfolio (US Polo, Tommy Hilfiger, Calvin Klein India licenses) — turnaround via portfolio rationalisation rather than a single new-format story." },
        kinds: { governance: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "A multi-brand turnaround is harder to verify than a single-format story like Trent's Zudio — check profitability brand-by-brand rather than the consolidated number.",
      },
    ],
  },

  {
    name: "Water EPC",
    stocks: [
      {
        ticker: "WABAG", company: "VA Tech Wabag",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "Established water/wastewater treatment EPC player benefiting from municipal and industrial water-treatment mandates." },
        kinds: { formalisation: true, demand: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: { noorderbook: false },
        notes: "EPC order books in water infrastructure have historically had thin, execution-dependent margins — the same false-positive check that applies to railway EPC names applies here.",
      },
      {
        ticker: "IONEXCHANG", company: "Ion Exchange (India)",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Diversified across water treatment chemicals, equipment and EPC — a broader base than pure-EPC peers." },
        kinds: { formalisation: true },
        operating: {},
        cash: { ocf: true },
        falsepositives: {},
        notes: "The chemicals and consumables business gives more recurring revenue than a pure EPC name — worth separating that recurring base from the lumpier project business.",
      },
      {
        ticker: "JASH", company: "Jash Engineering",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { leadingvar: "Makes water-control equipment (gates, screens, valves) rather than taking EPC execution risk itself — a component supplier to the same capex wave." },
        kinds: { product: true, formalisation: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Being a component supplier rather than an EPC contractor changes the risk profile — less exposed to project execution delays than Wabag or VPRPL, worth noting as a distinct kind of exposure.",
      },
      {
        ticker: "VPRPL", company: "Vishnu Prakash R Punglia",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { leadingvar: "Broader infrastructure EPC (water, roads, railways) rather than a water-pure-play — order book diversified across segments." },
        kinds: { demand: true, formalisation: true },
        operating: {},
        cash: {},
        falsepositives: { noorderbook: false },
        notes: "Newer and smaller than Wabag — the same order-book-versus-execution-capacity question applies, arguably with less of a track record to check it against.",
      },
    ],
  },

  {
    name: "Heavy Engineering Equipment",
    stocks: [
      {
        ticker: "GMMPFAUDLR", company: "GMM Pfaudler",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "Global leader in glass-lined process equipment for pharma and chemical plants — demand tracks capex cycles in those two industries." },
        kinds: { demand: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "A derivative play on pharma/chemical capex rather than a story of its own — check order inflow from those two end-industries specifically rather than reading this in isolation.",
      },
      {
        ticker: "HLEGLAS", company: "HLE Glascoat",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { leadingvar: "Smaller peer to GMM Pfaudler in the same glass-lined equipment niche, with more room to gain share." },
        kinds: { demand: true, product: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Same end-market dependency as GMM Pfaudler but less established — treat as the higher-risk, potentially higher-reward version of the same thesis.",
      },
    ],
  },

  {
    name: "CDMO",
    stocks: [
      {
        ticker: "SYNGENE", company: "Syngene International",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "no" },
        requirementNotes: { priceold: "Biocon-promoted, well-established contract research and manufacturing player — already a well-owned CDMO proxy in India." },
        kinds: { demand: true },
        operating: {},
        cash: { ocf: true },
        falsepositives: {},
        notes: "A benchmark large-cap CDMO name rather than a fresh discovery — useful as a reference point for the sector's growth rate.",
      },
      {
        ticker: "GLAND", company: "Gland Pharma",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Injectable-focused CDMO plus its own generics business, majority-owned by China's Fosun — a China+1 beneficiary narrative worth verifying against actual order wins." },
        kinds: { demand: true, formalisation: true },
        operating: {},
        cash: { ocf: true },
        falsepositives: { onecustomer: false },
        notes: "Check customer and geography concentration specifically — CDMO revenue can look diversified in aggregate while depending heavily on a small number of large innovator-company contracts.",
      },
      {
        ticker: "SUPRIYA", company: "Supriya Lifescience",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "API manufacturer moving up the value chain toward more complex, higher-margin molecules and export markets." },
        kinds: { product: true, formalisation: true },
        operating: { newproduct: true },
        cash: {},
        falsepositives: {},
        notes: "Smaller and more concentrated in a handful of API molecules than Gland or Syngene — check customer and molecule concentration before assuming the growth is broad-based.",
      },
      {
        ticker: "JUBLPHARMA", company: "Jubilant Pharmova",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "no", priceold: "yes" },
        requirementNotes: { cashevidence: "Carries a more complex, historically higher-debt structure across its CDMO, radiopharma and generics segments than pure-play peers — a balance-sheet check matters more here." },
        kinds: { demand: true, balancesheet: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "A multi-segment turnaround story (CDMO plus radiopharmaceuticals plus generics) — evaluate each segment's cash generation separately rather than trusting the consolidated picture alone.",
      },
    ],
  },
];
