/* ===================================================================
   PRESET SECTOR DATA
   Framework reads drafted from public order-book disclosures, brokerage
   notes and management commentary available as of early 2026. Treat
   these as a starting file, not a verdict — confirm the current
   quarter's numbers before acting, the same way the framework itself
   expects ongoing re-verification.
=================================================================== */

/* ===================================================================
   FULL SECTOR TAXONOMY (Screener.in classification)
   Every sector shows up in the dropdown. Only some have researched
   stock cards yet (see PRESET_SECTORS below) — the rest let you add
   a stock inline and build the file up as you go.
=================================================================== */
const ALL_SECTOR_NAMES = [
  "Aerospace & Defence", "Agro Chemicals", "Air Transport Service", "Alcoholic Beverages",
  "Auto Ancillaries", "Automobile", "Banks", "Bearings", "Cables",
  "Capital Goods - Electrical Equipment", "Capital Goods-Non Electrical Equipment",
  "Castings, Forgings & Fastners", "Cement", "Cement - Products", "Ceramic Products",
  "Chemicals", "Computer Education", "Construction", "Consumer Durables",
  "Credit Rating Agencies", "Crude Oil & Natural Gas", "Diamond, Gems and Jewellery",
  "Diversified", "Dry cells", "E-Commerce/App based Aggregator", "Edible Oil", "Education",
  "Electronics", "Engineering", "Entertainment", "ETF", "Ferro Alloys", "Fertilizers",
  "Finance", "Financial Services", "FMCG", "Gas Distribution", "Glass & Glass Products",
  "Healthcare", "Hotels & Restaurants", "Infrastructure Developers & Operators",
  "Infrastructure Investment Trusts", "Insurance", "IT - Hardware", "IT - Software",
  "Leather", "Logistics", "Marine Port & Services", "Media - Print/Television/Radio",
  "Mining & Mineral products", "Miscellaneous", "Non Ferrous Metals", "Oil Drill/Allied",
  "Online Media", "Packaging", "Paints/Varnish", "Paper", "Petrochemicals",
  "Pharmaceuticals", "Plantation & Plantation Products", "Plastic products",
  "Plywood Boards/Laminates", "Power Generation & Distribution", "Power Infrastructure",
  "Printing & Stationery", "Quick Service Restaurant", "Railways",
  "Readymade Garments/ Apparells", "Real Estate Investment Trusts", "Realty",
  "Refineries", "Refractories", "Retail", "Sanitaryware", "Ship Building", "Shipping",
  "Steel", "Stock/ Commodity Brokers", "Sugar", "Telecom-Handsets/Mobile",
  "Telecomm Equipment & Infra Services", "Telecomm-Service", "Textiles",
  "Tobacco Products", "Trading", "Tyres",
];

const PRESET_SECTORS = [
  {
    name: "Aerospace & Defence",
    stocks: [
      {
        ticker: "BEL", company: "Bharat Electronics",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "no" },
        requirementNotes: {
          relevant: "Sole/lead supplier on most Indian radar, EW and comms programmes — hard to displace.",
          leadingvar: "DAC approvals at an all-time high in FY26; order-awarding momentum expected to keep rising into FY27/28.",
          twoconfirm: "Disclosed order book (~₹76,000cr+) and rising capex allocation both point the same way.",
          cashevidence: "PSU with steady dividends and healthy margins, but working capital scales with the size of the book.",
          priceold: "This is the weak leg — the story is already the market's consensus pick in defence electronics.",
        },
        kinds: { demand: true, formalisation: true },
        operating: { volumes: true, repeat: true, capacityutil: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Book-to-bill sits around 4x industry-wide per brokerage notes (Aug 2026) — the open question for BEL specifically is no longer 'will orders come' but 'can execution keep pace.' Best used as a Stage-4 consensus holding, not a fresh discovery.",
      },
      {
        ticker: "SOLARINDS", company: "Solar Industries",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "Defence ordnance/explosives arm ramping off a much smaller base than BEL/HAL, plus export growth.",
          twoconfirm: "Management guidance of 25-30% revenue growth for FY26, alongside a defence order book still small relative to the civil explosives business.",
          priceold: "Already up sharply over five years — check whether the current price still leaves room, or has run ahead of the ramp.",
        },
        kinds: { demand: true, formalisation: true },
        operating: { repeat: true, marketshare: true },
        cash: { selffunded: true, roic: true },
        falsepositives: {},
        notes: "The core civil explosives business is cash-generative and appears to be funding the defence capacity build without heavy dilution — worth checking segment-wise disclosure to confirm this isn't manufactured through the parent's cash rather than the defence unit's own economics.",
      },
      {
        ticker: "BDL", company: "Bharat Dynamics",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "Missile/ammunition PSU with brokerages guiding even higher growth (25-30%) than larger DPSU peers off a smaller base.",
          twoconfirm: "Order book growth is disclosed; margin trajectory alongside it is less consistently confirmed quarter to quarter.",
        },
        kinds: { demand: true, formalisation: true },
        operating: { repeat: true },
        cash: {},
        falsepositives: { noorderbook: false },
        notes: "Smaller and less consensus-crowded than BEL/HAL — worth the two-question test from the framework: who will buy the output, and at what margin, before treating the order book alone as confirmation.",
      },
    ],
  },

  {
    name: "Capital Goods - Electrical Equipment",
    stocks: [
      {
        ticker: "WAAREEENER", company: "Waaree Energies",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "India's solar module manufacturing capacity roughly doubled industry-wide in a year (74GW to 172GW by March 2026) as ALMM rules shift domestic demand toward domestic makers.",
          twoconfirm: "Capacity expansion and the ALMM-driven order shift are two independent, publicly verifiable confirmations.",
          cashevidence: "Capital-intensive ramp — check whether the expansion is debt-funded or self-funded before trusting the growth.",
        },
        kinds: { capacity: true, formalisation: true },
        operating: { capacityutil: true, volumes: true },
        cash: {},
        falsepositives: {},
        notes: "This is a capex-to-cash bridge story first — use section F to track where Waaree's incremental capacity actually sits (commissioned vs. utilised vs. cash-generating) rather than reading the capacity announcement itself as demand.",
      },
      {
        ticker: "SUZLON", company: "Suzlon Energy",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "partial" },
        requirementNotes: {
          leadingvar: "Per ICRA (Jan 2026), wind OEM order books have surpassed annual manufacturing capacity industry-wide — a genuine capacity-utilisation confirmation, not a story.",
          cashevidence: "Suzlon's own balance-sheet repair (debt paydown after its earlier restructuring) is a textbook example of the framework's balance-sheet-repair kind of inflection.",
        },
        kinds: { capacity: true, balancesheet: true },
        operating: { capacityutil: true, volumes: true },
        cash: { debtfalling: true, ocf: true },
        falsepositives: {},
        notes: "A rare case where two different kinds of inflection (capacity utilisation + balance-sheet repair) are confirming each other at once — worth the higher conviction that implies, provided the order book keeps converting into billed revenue.",
      },
      {
        ticker: "PREMIERENE", company: "Premier Energies",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "Integrated solar cell and module capacity ramp, riding the same ALMM-driven domestic shift as Waaree.",
          twoconfirm: "Newer listing — fewer quarters of disclosed data to independently cross-check the capacity story yet.",
        },
        kinds: { capacity: true, formalisation: true },
        operating: { capacityutil: true },
        cash: {},
        falsepositives: {},
        notes: "Track the same capex-to-cash bridge as Waaree. Being a more recently listed, less-covered name than Waaree, there's more room for this to still be genuinely Stage 2 rather than already priced in.",
      },
      {
        ticker: "TRIL", company: "Transformers & Rectifiers (India)",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "Transformer order books across the industry are at multi-year highs on T&D capex, renewable integration and data-centre power demand.",
          twoconfirm: "Order book plus rising industry-wide capacity utilisation for transformer makers.",
        },
        kinds: { capacity: true, demand: true },
        operating: { capacityutil: true, volumes: true },
        cash: {},
        falsepositives: {},
        notes: "Smaller-cap names in this space are still mid-way through their own capex-to-cash bridge — check where this one specifically sits (commissioning vs. utilisation) before assuming the whole sector's tailwind applies equally.",
      },
      {
        ticker: "GEVERNOVA", company: "GE Vernova T&D India",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "no" },
        requirementNotes: { priceold: "Large, well-covered grid-equipment name — the T&D capex story is already the market's consensus view here." },
        kinds: { demand: true },
        operating: { volumes: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "A benchmark large-cap for the grid-capex theme rather than a fresh Stage-2 candidate.",
      },
    ],
  },

  {
    name: "Auto Ancillaries",
    stocks: [
      {
        ticker: "SONACOMS", company: "Sona BLW Precision Forgings",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {
          leadingvar: "BEV driveline revenue share has been rising as a disclosed proportion of the overall mix, ahead of it showing up as a step-change in headline margins.",
          twoconfirm: "Company discloses both the BEV order book and the BEV revenue-mix percentage separately — two independent reads on the same shift.",
        },
        kinds: { product: true, demand: true },
        operating: { newproduct: true, marketshare: true },
        cash: {},
        falsepositives: {},
        notes: "Capex-heavy expansion to support new EV programmes — check free cash flow against the capex run-rate before assuming the growth is self-funded.",
      },
      {
        ticker: "UNOMINDA", company: "Uno Minda",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Steady content-per-vehicle gains across sensors, alloy wheels and EV components rather than one single product bet." },
        kinds: { demand: true, product: true },
        operating: { marketshare: true, volumes: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Diversified enough that no single product failure breaks the thesis — but that same diversification also makes it a slower, more consensus-priced compounder than a single-product Stage-2 bet.",
      },
      {
        ticker: "MOTHERSON", company: "Samvardhana Motherson International",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "no" },
        requirementNotes: { priceold: "Large, globally diversified tier-1 — already a conference-favourite auto-components name, so the crowd has largely priced the story in." },
        kinds: { demand: true },
        operating: { marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Useful as a scale benchmark for the sector rather than a fresh inflection candidate — most of the asymmetry here has already been arbitraged away.",
      },
    ],
  },

  {
    name: "Electronics",
    stocks: [
      {
        ticker: "DIXON", company: "Dixon Technologies",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "partial", priceold: "no" },
        requirementNotes: {
          leadingvar: "Shifting from pure contract assembly (thin margin) toward components — display modules, camera modules — which carry structurally higher margin.",
          priceold: "Already a well-owned PLI/EMS proxy; the market prices continued margin mix-shift as the base case.",
        },
        kinds: { product: true, formalisation: true },
        operating: { newproduct: true, marketshare: true },
        cash: {},
        falsepositives: {},
        notes: "The thesis now lives in the mix shift (components rising as % of revenue), not in headline revenue growth — track that percentage specifically each quarter.",
      },
      {
        ticker: "KAYNES", company: "Kaynes Technology",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "no" },
        requirementNotes: {
          leadingvar: "Core EMS business is confirmed and growing; the large semiconductor/OSAT packaging capex is still in the announced-to-commissioning phase.",
          twoconfirm: "Treat this as two separate cases stacked together — don't let confidence in the base EMS business bleed into confidence about the unproven semiconductor bet.",
        },
        kinds: { product: true, capacity: true },
        operating: { newproduct: true },
        cash: {},
        falsepositives: { noorderbook: false },
        notes: "A clean example of the framework's own warning: a capex announcement and a full order book are not demand. Use the capex-to-cash bridge below specifically for the semiconductor unit, separate from the core EMS read.",
      },
      {
        ticker: "AMBER", company: "Amber Enterprises",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "RAC (room AC) EMS plus a push into compressors — vertical integration similar in shape to Dixon's mix-shift story." },
        kinds: { product: true, formalisation: true },
        operating: { newproduct: true },
        cash: {},
        falsepositives: {},
        notes: "Demand is seasonal (summer-linked) — be careful not to read a strong summer quarter alone as a structural inflection; look for the compressor vertical-integration margin specifically.",
      },
    ],
  },

  {
    name: "Capital Goods-Non Electrical Equipment",
    stocks: [
      {
        ticker: "TRITURBINE", company: "Triveni Turbine",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Industrial steam turbine demand from both domestic capex and exports, converting steadily into revenue." },
        kinds: { demand: true },
        operating: { volumes: true, marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Longer, steadier track record than the newer transformer names — less asymmetric, but the confirmation is more mature.",
      },
      {
        ticker: "KIRLOSENG", company: "Kirloskar Pneumatic",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: {},
        kinds: { demand: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Smaller and less-covered industrial capex play — treat as an early, unconfirmed candidate rather than a settled read.",
      },
    ],
  },

  {
    name: "Railways",
    stocks: [
      {
        ticker: "TITAGARH", company: "Titagarh Rail Systems",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "no" },
        requirementNotes: {
          leadingvar: "Vande Bharat and metro coach order book is large and disclosed, but the stock already re-rated heavily in 2023-24 on that same story.",
          priceold: "Execution and margin delivery are now the swing factor, not order visibility — classic Stage 4.",
        },
        kinds: { demand: true, formalisation: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: { noorderbook: false },
        notes: "Watch margins specifically — an order book with no clear margin visibility behind it is one of the framework's named false positives, and railway EPC margins have historically been thin.",
      },
      {
        ticker: "RVNL", company: "Rail Vikas Nigam",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "no" },
        requirementNotes: {
          leadingvar: "Steady EPC order inflow from Indian Railways as a PSU project-execution arm.",
          priceold: "Already consensus-recognised — most of the operating story is in the price.",
        },
        kinds: { demand: true, formalisation: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: { noorderbook: false },
        notes: "Order inflow is steady but margins are thin and execution-dependent — the framework's 'order book has no execution capacity or margin visibility' flag deserves a real check here, not just a box-tick.",
      },
      {
        ticker: "IRCON", company: "Ircon International",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { priceold: "Less consensus-crowded than RVNL or Titagarh — more room left if the same order-book story plays out here too." },
        kinds: { demand: true, formalisation: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Smaller and less-owned than its railway EPC peers — worth the same margin-visibility check, but starting from a less priced-in base.",
      },
    ],
  },

  {
    name: "Engineering",
    stocks: [
      {
        ticker: "THERMAX", company: "Thermax",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "Diversifying order book into green hydrogen and chemicals-linked capex on top of its traditional energy/environment business." },
        kinds: { demand: true, capacity: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: {},
        notes: "The new-energy order book is real but still small relative to the base business — check it's not being used to justify a re-rating of the whole company before it's material.",
      },
      {
        ticker: "PRAJIND", company: "Praj Industries",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Ethanol-blending policy has driven a multi-year domestic capex cycle for distillery equipment." },
        kinds: { demand: true, formalisation: true },
        operating: { volumes: true, repeat: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "A formalisation/regulation-driven inflection — the key falsifier to watch is any slowdown in the blending mandate itself, since the order book depends on that policy holding.",
      },
    ],
  },

  {
    name: "Consumer Durables",
    stocks: [
      {
        ticker: "VOLTAS", company: "Voltas",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "RAC demand plus PLI-linked component localisation, similar to the Amber/Dixon EMS story from the buyer's side." },
        kinds: { demand: true, formalisation: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: {},
        notes: "Same seasonal caution as Amber applies — separate a genuinely hot summer quarter from a durable share gain.",
      },
      {
        ticker: "HAVELLS", company: "Havells India",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "no" },
        requirementNotes: { priceold: "Large, well-owned consumer electricals name — already priced as a quality compounder." },
        kinds: { demand: true },
        operating: { marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "A benchmark quality name rather than a fresh inflection candidate.",
      },
      {
        ticker: "CROMPTON", company: "Crompton Greaves Consumer Electricals",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {},
        kinds: { demand: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Turnaround-in-progress story (management and distribution changes) — check governance/execution confirmations specifically before treating it as confirmed.",
      },
    ],
  },

  {
    name: "Textiles",
    stocks: [
      {
        ticker: "GOKEX", company: "Gokaldas Exports",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "yes" },
        requirementNotes: { leadingvar: "Apparel export order wins from US/Europe brands looking to diversify sourcing away from China ('China+1')." },
        kinds: { demand: true, capacity: true },
        operating: { volumes: true, newproduct: true },
        cash: {},
        falsepositives: { onecustomer: false },
        notes: "Check customer concentration specifically — a China+1 order win from one or two large brands can look like structural demand while really being a single-customer story.",
      },
      {
        ticker: "KPRMILL", company: "KPR Mill",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "yes", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Vertically integrated (yarn to garment) with garmenting capacity expansion running ahead of peers." },
        kinds: { demand: true, capacity: true },
        operating: { volumes: true, capacityutil: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "Vertical integration gives more independent confirmation points than a pure garmenter like Gokaldas — a genuinely stronger evidence base.",
      },
      {
        ticker: "WELSPUNLIV", company: "Welspun Living",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: {},
        kinds: { demand: true },
        operating: {},
        cash: {},
        falsepositives: { onecustomer: false },
        notes: "Home textiles depend heavily on a handful of large US retail relationships — the same single-customer flag as Gokaldas applies, arguably more so.",
      },
    ],
  },

  {
    name: "Insurance",
    stocks: [
      {
        ticker: "ICICIGI", company: "ICICI Lombard General Insurance",
        stage: 4,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "yes", priceold: "no" },
        requirementNotes: { priceold: "Large, well-covered general insurer — insurance penetration story is already the market's base case here." },
        kinds: { formalisation: true },
        operating: { marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "A benchmark quality name in general insurance rather than a fresh inflection candidate.",
      },
      {
        ticker: "STARHEALTH", company: "Star Health and Allied Insurance",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "no", priceold: "yes" },
        requirementNotes: { cashevidence: "Claims ratio and combined ratio trends need close tracking — health insurers can show premium growth while underwriting quality deteriorates." },
        kinds: { formalisation: true, demand: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: { costcollapse: false },
        notes: "This is the sector's clearest case of the framework's own warning — 'inflection guilty until proven innocent' — because premium growth alone says nothing about claims experience. Check the combined ratio before the topline.",
      },
      {
        ticker: "NIVABUPA", company: "Niva Bupa Health Insurance",
        stage: 1,
        requirements: { relevant: "yes", leadingvar: "no", twoconfirm: "no", cashevidence: "no", priceold: "yes" },
        requirementNotes: { leadingvar: "Newer listing still building distribution scale — story stage, limited independent confirmation yet." },
        kinds: { formalisation: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Too early for most of the framework's confirmation checks — treat as a name to revisit once a few more quarters of claims and distribution data exist.",
      },
    ],
  },

  {
    name: "Logistics",
    stocks: [
      {
        ticker: "CONCOR", company: "Container Corporation of India",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "partial", priceold: "partial" },
        requirementNotes: { leadingvar: "Dedicated Freight Corridor (DFC) sections are commissioning progressively, each one a potential step-change in rail logistics volume and transit time." },
        kinds: { capacity: true, formalisation: true },
        operating: { volumes: true },
        cash: {},
        falsepositives: {},
        notes: "Structurally similar to the capex-to-cash bridge — track which DFC sections are actually commissioned and carrying volume versus still under construction, rather than the overall project announcement.",
      },
      {
        ticker: "TCIEXP", company: "TCI Express",
        stage: 3,
        requirements: { relevant: "yes", leadingvar: "yes", twoconfirm: "partial", cashevidence: "yes", priceold: "partial" },
        requirementNotes: { leadingvar: "Organised express logistics gaining share from unorganised operators post-GST/e-way bill formalisation." },
        kinds: { formalisation: true, demand: true },
        operating: { marketshare: true },
        cash: { ocf: true },
        falsepositives: {},
        notes: "A cleaner formalisation story than most — the mechanism (GST compliance favouring organised players) is structural rather than cyclical.",
      },
      {
        ticker: "MAHLOG", company: "Mahindra Logistics",
        stage: 2,
        requirements: { relevant: "yes", leadingvar: "partial", twoconfirm: "partial", cashevidence: "no", priceold: "yes" },
        requirementNotes: { cashevidence: "Asset-light 3PL model — margins have historically been thin; check whether scale is actually converting to profitability." },
        kinds: { formalisation: true },
        operating: {},
        cash: {},
        falsepositives: {},
        notes: "Same formalisation tailwind as TCI Express, but thinner margins historically — the moat/right-to-win question in section E matters more here.",
      },
    ],
  },
];
